version: '3.8'

services:
  frontend:
    image: luiscepeda7/calificaciones-frontend:latest
    container_name: calificaciones-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - calificaciones-network

networks:
  calificaciones-network:
    external: true
    name: calificaciones-network
